# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
arr = arr.reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr3 = np.vstack((arr1,arr2))
arr3 = arr3.astype('int32')
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr4 = np.hstack((arr1,arr2))
arr4 = arr4.astype('int32')
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
arr = arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr6 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[22 13 13 17 17]
 [ 5 24 17  4  4]
 [18 22  7 17  3]
 [ 3 20  2 22 20]
 [24 16  6  8  3]]


Square of Array: 

[[484 169 169 289 289]
 [ 25 576 289  16  16]
 [324 484  49 289   9]
 [  9 400   4 484 400]
 [576 256  36  64   9]]


## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Mean of Array: \n")
print(arr8.mean())

Original Array: 

[[15 16  1  9 16 18]
 [16  4 18  5 13  3]
 [10  6  9  4  9 19]
 [ 8 11  4 10 12 19]
 [ 1 16 15 10 15 12]]


Mean of Array: 

10.8


## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr8))

Original Array: 

[[15 16  1  9 16 18]
 [16  4 18  5 13  3]
 [10  6  9  4  9 19]
 [ 8 11  4 10 12 19]
 [ 1 16 15 10 15 12]]


Standard deviation of Array: 

5.4


## Question:10

### Find the median of the previous array in Q8?

In [11]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Median of Array: \n")
print(np.median(arr8))

Original Array: 

[[15 16  1  9 16 18]
 [16  4 18  5 13  3]
 [10  6  9  4  9 19]
 [ 8 11  4 10 12 19]
 [ 1 16 15 10 15 12]]


Median of Array: 

10.5


## Question:11

### Find the transpose of the previous array in Q8?

In [13]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr8))

Original Array: 

[[15 16  1  9 16 18]
 [16  4 18  5 13  3]
 [10  6  9  4  9 19]
 [ 8 11  4 10 12 19]
 [ 1 16 15 10 15 12]]


Transpose of Array: 

[[15 16 10  8  1]
 [16  4  6 11 16]
 [ 1 18  9  4 15]
 [ 9  5  4 10 10]
 [16 13  9 12 15]
 [18  3 19 19 12]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [14]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[13  8 18 18]
 [14 13 19  6]
 [ 2  4  4 17]
 [11 12  7 10]]


Sum of diagonal elements of Array: 

40


## Question:13

### Find the determinant of the previous array in Q12?

In [15]:
print("Original Array: \n")
print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[13  8 18 18]
 [14 13 19  6]
 [ 2  4  4 17]
 [11 12  7 10]]


Determinant of Array: 

10950.999999999995


## Question:14

### Find the 5th and 95th percentile of an array?

In [16]:
print("Original Array: \n")
print (arr7)
print("\n")
print(f"5th percentile of array: {np.percentile(arr7, 5)}")
print(f"95th percentile of array: {np.percentile(arr7, 95)}")

Original Array: 

[[13  8 18 18]
 [14 13 19  6]
 [ 2  4  4 17]
 [11 12  7 10]]


5th percentile of array: 3.5
95th percentile of array: 18.25


## Question:15

### How to find if a given array has any null values?

In [17]:
np.isnan(arr7).any()

False